[build]
  command = "npm ci && npm run build:netlify"
  publish = "dist"

# Force Node.js 18 which is more stable with vue-tsc
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_YARN = "false"
  NETLIFY_RESTORE_CACHE = "true"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
