[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "dist"

# Force Node.js 16 which is more stable and memory-efficient
[build.environment]
  NODE_VERSION = "16"
  NODE_OPTIONS = "--max_old_space_size=2048"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
