[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "dist"

# Use Node.js 14 which is very stable and memory-efficient
[build.environment]
  NODE_VERSION = "14"
  NODE_OPTIONS = "--max_old_space_size=1024"
  NPM_FLAGS = "--no-optional --no-fund --no-audit"
  NETLIFY_USE_YARN = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
